name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature] <short description>"
labels: [feature-request]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: 📄 Feature description
      description: Clearly describe the feature you'd like to request.
      placeholder: "What would you like to see added or changed?"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 🚀 Motivation
      description: Why is this feature important or useful?
      placeholder: "Explain the problem this feature solves, or the value it adds."
  
  - type: textarea
    id: alternatives
    attributes:
      label: 🔁 Alternatives
      description: Have you considered other solutions or workarounds?

  - type: textarea
    id: context
    attributes:
      label: ➕ Additional context
      description: Add links, screenshots, or other context here.

