decoder_model_path: sam2_hiera_small.decoder.onnx
display_name: Segment Anything 2 (Hiera-Small)
encoder_model_path: sam2_hiera_small.encoder.onnx
input_size: 1024
max_height: 1024
max_width: 1024
name: sam2_hiera_small_20240803
type: segment_anything
