name: Build Flutter Windows App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and extract Flutter 3.19.0
        run: |
          curl -s -o flutter.zip https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.19.0-stable.zip
          7z x flutter.zip -oC:\flutter

      - name: Show Flutter & Dart version
        run: C:\flutter\flutter\bin\flutter.bat --version

      - name: Enable Windows desktop support
        run: C:\flutter\flutter\bin\flutter.bat config --enable-windows-desktop

      - name: Install dependencies
        run: C:\flutter\flutter\bin\flutter.bat pub get

      - name: Build Windows app (EXE)
        run: C:\flutter\flutter\bin\flutter.bat build windows --release

      - name: Install WiX Toolset for MSIX
        run: choco install wixtoolset -y

      - name: Create MSIX installer
        run: C:\flutter\flutter\bin\flutter.bat pub run msix:create

      - name: Upload Windows EXE build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/runner/Release/

      - name: Upload MSIX installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: build/windows/runner/msix/*.msix
