name: Build Flutter Windows App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'  # Dart 3.7.3 included
          channel: stable

      - name: Show Flutter & Dart version
        run: flutter --version

      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze (optional)
        run: flutter analyze

      - name: Run tests (optional)
        run: flutter test

      - name: Build Windows app
        run: flutter build windows --release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/runner/Release/
